FROM debian:8

MAINTAINER IVÁN DE PAZ CENTENO <ipazc@unileon.es, ivan@sockhost.net>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get install -y python3 python3-pip python3-flask python3-pil wget xvfb 

RUN pip3 install selenium pyvirtualdisplay bs4 xvfbwrapper 

RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz -O /tmp/geckodriver-v0.16.1.tar.gz \
    && tar xvzf /tmp/geckodriver-v0.16.1.tar.gz -C /usr/bin/ \
    && chmod +x /usr/bin/geckodriver


RUN echo '# Backports\n\
deb http://ftp.fr.debian.org/debian jessie-backports main contrib non-free\n\
deb-src http://ftp.fr.debian.org/debian jessie-backports main contrib non-free\n' \
>>  /etc/apt/sources.list \
 && echo '# Mozilla\n\
deb http://mozilla.debian.net/ jessie-backports firefox-release\n\
deb-src http://mozilla.debian.net/ jessie-backports firefox-release\n' \
>> /etc/apt/sources.list

RUN apt-get install -y pkg-mozilla-archive-keyring debian-keyring  \
 && apt-get update \
 && apt-get install firefox apache2 -y 
 
RUN apt-get remove wget -y 
RUN apt-get autoremove -y 
RUN apt-get clean 
RUN rm -r /tmp/*
RUN rm /var/www/html/index.html 
