FROM debian:8

MAINTAINER IVÁN DE PAZ CENTENO <ipazc@unileon.es, ivan@sockhost.net>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get install -y python3 python3-pip python3-flask python3-pil wget xvfb \
 && pip3 install selenium pyvirtualdisplay bs4 xvfbwrapper \

RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz -O /tmp/geckodriver-v0.16.1.tar.gz \
    && tar /tmp/geckodriver-v0.16.1.tar.gz xvzf -C /usr/bin/ \
    && chmod +x /usr/bin/geckodriver


RUN echo "# Backports
deb http://ftp.fr.debian.org/debian jessie-backports main contrib non-free
deb-src http://ftp.fr.debian.org/debian jessie-backports main contrib non-free
" >> /etc/apt/sources.list \
 && echo "# Mozilla
deb http://mozilla.debian.net/ jessie-backports firefox-release
deb-src http://mozilla.debian.net/ jessie-backports firefox-release
" >> /etc/apt/sources.list

RUN apt-get install -y pkg-mozilla-archive-keyring debian-keyring  \
 && apt-get update \
 && apt-get install firefox apache2 -y \
 && rm /var/www/html/index.html \
 && apt-get remove wget \
 && apt-get autoremove \
 && apt-get clean \
 && rm -r /tmp/*